### ISSUE TITLE
xml is obsolete deprecated serializable format

### ISSUE THREAD

**Issue by TheSquidCombatant** [Pennywise007/ext#1]
You should use json or yaml as a human-readable format. Or binary serialization for speed dependent operations.

**Comment by TheSquidCombatant** [comment]
I mean these days there are only two reasons to use xml:

1. third party service does not support anything else than xml
2. are you so scared of getting broken data that insert a hash into each tag

```xml
<outer crc32="...">
	<inner1 crc32="...">
		...
	</inner1>	
	...	
	<innerN crc32="...">
		...
	</innerN>
</outer>
```

**Comment by TheSquidCombatant** [comment]
I suggest adding more different formats and serialization options.

**Comment by Pennywise007** [comment]
XML was removed and I added json support.
