### ISSUE TITLE
cyclic calls problem with event dispatcher

### ISSUE THREAD

**Issue by TheSquidCombatant** [Pennywise007/ext#2]
Motivation
Problems with cyclic spawning of events are problems with application code using the event dispatcher, it is true. But you don`t give the application code a tool to solve this problem.

Scenarios
For example, you have a logger that subscribed to exception events and produce exception event by itself while writing log.

Suggestion
I suggest adding an immutable parameter ```ISender``` to the event processing methods signature. This will help the application code to build the logic for processing cyclic calls.

**Comment by Pennywise007** [comment]
I don't see the need to add mandatory parameters; what you want is already supported by the dispatcher.

```c++

struct ISender {};

struct IException : ext::events::IBaseEvent {
    virtual void OnException(ISender* sender, int errorCode) = 0;
};

struct Logger : ISender, ext::events::ScopeSubscription<IException> {
    void OnException(ISender* sender, int errorCode) override {
        last_error_code_ = errorCode;
       
        if (sender == this)
            return;
        ext::send_event(&IException::OnException, this, 404);
    }

    int last_error_code_ = 0;
};

TEST(dispatcher_test, logger_exceptions)
{
    Logger logger;

    ext::send_event(&IException::OnException, nullptr, 101);

    EXPECT_EQ(logger.last_error_code_, 404);
}
```
