### ISSUE TITLE
undefined behavior of event subscribers

### ISSUE THREAD

**Issue by TheSquidCombatant** [Pennywise007/ext#4]
Motivation
As a subscriber to events, I am not interested in how the event notification will be physically sent (in several threads or in one). What matters to me is how can I control whether event handlers are fired logically sequential or in parallel. Parallel means that each subscriber will receive notification about the event, regardless of how the event was processed by other subscribers. Sequential means that subscribers have an order, and the subscriber that runs before can interrupt the notification of subsequent subscribers.

Scenarios
One example of parallel notification. Several loggers subscribed to the error event. I want every subscribed loggers try to log. Other example of sequential notification. Several hierarchical handlers for pressing keyboard shortcuts on the form. I want the first suitable one process and stop continuation.

Suggestion
I suggest to divide event subscriptions into two types: queue for sequential subscriber notification and set for parallel subscriber notification. For sequential notification, to explicitly control passing the notification subscriber by subscriber, I suggest to add the ```IResult``` parameter to the signature of the sequential subscriber handler method and require each of subscribers to return it configured. For parallel notification, to explicitly monitor execution success, I suggest accumulate exceptions from different subscribers and throw them in the end as a single object ```AggregateException```.

**Comment by Pennywise007** [comment]
I added a separate function [call_for_every_recipient](https://github.com/Pennywise007/ext/blob/main/include/ext/core/dispatcher.h#L93) which will allow you to pass your callback to all subscribed recipients. It should solve all your problems, you will be able to handle function results, catch exceptions, and call them in different orders.
