### ISSUE TITLE
insufficient return from async send event method

### ISSUE THREAD

**Issue by TheSquidCombatant** [Pennywise007/ext#5]
It would be useful for an asynchronous method to return not void, but an async object of the notification task. So we could check the execution status by accessing the fields of task object. I suggest to return an ```ITask``` object which store the status and an exception (if exception occurred during processing). And fill all fields of the ```ITask``` object asynchronously from notification processing thread.

**Comment by Pennywise007** [comment]
Reworked void to std::future, thank you for the idea.
